"""empty message

Revision ID: 49486a564338
Revises: 780abeed11a5
Create Date: 2020-08-15 15:02:33.606650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49486a564338'
down_revision = '780abeed11a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('slug', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'slug')
    # ### end Alembic commands ###
