"""empty message

Revision ID: 72b00dae55b0
Revises: be0b3934e971
Create Date: 2020-08-05 14:51:39.850821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72b00dae55b0'
down_revision = 'be0b3934e971'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_name_key', 'users', type_='unique')
    op.drop_column('users', 'progress')
    op.drop_column('users', 'current_course')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_course', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('progress', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('users_name_key', 'users', ['name'])
    # ### end Alembic commands ###
