"""changing more resource to course

Revision ID: 76c2e57cf392
Revises: b14fa390415b
Create Date: 2020-07-23 17:02:24.974453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76c2e57cf392'
down_revision = 'b14fa390415b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_course', sa.Integer(), nullable=True))
        batch_op.drop_column('parent_resource')

    with op.batch_alter_table('steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_course', sa.Integer(), nullable=True))
        batch_op.drop_column('parent_resource')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_resource', sa.INTEGER(), nullable=True))
        batch_op.drop_column('parent_course')

    with op.batch_alter_table('stages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_resource', sa.INTEGER(), nullable=True))
        batch_op.drop_column('parent_course')

    # ### end Alembic commands ###
