"""empty message

Revision ID: 780abeed11a5
Revises: 1e2007579834
Create Date: 2020-08-14 18:54:21.104272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '780abeed11a5'
down_revision = '1e2007579834'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('author', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'author')
    # ### end Alembic commands ###
