"""empty message

Revision ID: 8d1b84e58324
Revises: be0b3934e971
Create Date: 2020-08-05 14:44:11.928832

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8d1b84e58324'
down_revision = 'be0b3934e971'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'progress',
               existing_type=sa.VARCHAR(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('users', 'current_course')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_course', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('users', 'progress',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
