"""test

Revision ID: be0b3934e971
Revises: 
Create Date: 2020-07-27 14:43:03.967126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be0b3934e971'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stages', 'order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('steps', 'order',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('steps', 'order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('stages', 'order',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
