"""empty message

Revision ID: daef3a118908
Revises: 8da8ae614ab4
Create Date: 2020-08-29 19:15:00.656653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daef3a118908'
down_revision = '8da8ae614ab4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('draft', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'draft')
    # ### end Alembic commands ###
