"""empty message

Revision ID: f606648efb88
Revises: 72b00dae55b0
Create Date: 2020-08-06 09:57:39.107377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f606648efb88'
down_revision = '72b00dae55b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('steps', sa.Column('levels', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('steps', 'levels')
    # ### end Alembic commands ###
